language: c
script: 
  - echo "Running SCons"
  - scons
  - echo "Cleaning with SCons"
  - scons -c
  - echo "Running Make"
  - make
  - echo "Cleaning with Make"
  - make clean
notifications:
  email:
    on_success: never
    on_failure: always
