Import("matLib")

env = Environment(CPPPATH=["include", "#matrixlibrary/include"],
                  CFLAGS=["-Wall", "-Wextra", "-pedantic", "--std=c99"])

objs = []

for obj in Glob("src/*.c"):
    objs.append(env.Object(obj))

for test in Glob("src/tests/*.c"):
    env.Program([test] + objs, LIBS = matLib)
