env = Environment(CPPPATH="include",
                  CFLAGS=["-Wall", "-Wextra", "-pedantic", "--std=c99"])

matLib = env.StaticLibrary("src/matLib.c")

for test in Glob("src/tests/*.c"):
    env.Program(test, LIBS = matLib)
     
Return("matLib")
