env = Environment(CPPPATH="include",
                  CFLAGS=["-Wall", "-Wextra", "-pedantic", "--std=c99"])

matLib = env.StaticLibrary("src/matLib.c")

tests = []

for test in Glob("src/tests/*.c"):
    tests.append(env.Program(test, LIBS = matLib))
     
Return("matLib")
